### ISSUE TITLE
Clarify meaning of https://tycho.eclipseprojects.io/doc/3.0.0/tycho-ds-plugin/declarative-services-mojo.html#enabled

### ISSUE THREAD

**Issue by kwin** [eclipse-tycho/tycho#1468]
According to https://tycho.eclipseprojects.io/doc/3.0.0/tycho-ds-plugin/declarative-services-mojo.html#enabled there is a plugin parameter called `enabled`. But the description is very vague and in fact the according field doesn't seem to be evaluated: https://github.com/eclipse-tycho/tycho/blob/0f790c7c2498f6de0344d5ad1f7c0cc685c2ef2f/tycho-ds-plugin/src/main/java/org/eclipse/tycho/ds/DeclarativeServicesMojo.java#L65.

Is this used anywhere via reflection or can this private field just be removed?
It seems redundant as there is already https://github.com/eclipse-tycho/tycho/blob/0f790c7c2498f6de0344d5ad1f7c0cc685c2ef2f/tycho-ds-plugin/src/main/java/org/eclipse/tycho/ds/DeclarativeServicesMojo.java#L71.

**Comment by laeubi** [comment]
In Eclipse PDE you can enable DS processing for a single project by config file, or by global setting. The mojo parameter is there so that you can configure this on the mojo level and the parameter is visible to tools that scan the mojo parameters to give auto-completion and documentation.

> Is this used anywhere via reflection or can this private field just be removed?
It is evaluated here: 
https://github.com/eclipse-tycho/tycho/blob/master/tycho-core/src/main/java/org/eclipse/tycho/artifacts/configuration/DeclarativeServiceConfigurationReader.java

> It seems redundant as there is already

- `enable` = `false` (the default) will only process projects that have explicit project settings enabled DS processing
- `enable` = `true` in the mojo config will enable it for all projects except fro those that have an explicit disabling per-project configuration
- `skip` = `true` will disable processing for all projects regardless of their configuration settings

If you like feel free to open a PR with more user-centric documentation on that Mojo, developers are very bad documentation-writers because they always think it should be obvious :-)

**Comment by kwin** [comment]
Thanks for the hint, will try to come up with a documentation PR.
