### ISSUE TITLE
Tycho 3.0.0 download speed is much slower as 2.7.5 if mirrors are used

### ISSUE THREAD

**Issue by Phillipus** [eclipse-tycho/tycho#1631]
A Tycho 2.7.5 build of our product takes just 3 and a half minutes compared with about 8 minutes on Tycho 3.0.0. Each build was timed with an empty `.m2` directory. The extra time is spent downloading the artefacts.

Is there more going on with 3.0.0, or perhaps some new settings that might improve speed?

**Comment by laeubi** [comment]
> Is there more going on with 3.0.0, or perhaps some new settings that might improve speed?

We generally enable all settings that deliver best performance, but of course it depends on the actual setup.

What would be more interesting is how it performs after the inital download, because otherwise it even depends more on the setup and used servers.

**Comment by Phillipus** [comment]
Hi, after the initial download it's a about the same time to compile and assemble in both versions. But for some reason, the download of all the dependencies is slower on 3.0.0.

**Comment by Phillipus** [comment]
I ran it with the `-X` debug option and noticed that the slow down in 3.0.0 is at these points:

`[DEBUG] Writing P2 metadata for osgi.bundle,com.ibm.icu,67.1.0 to .m2\repository\p2\osgi\bundle\com.ibm.icu\67.1.0\com.ibm.icu-67.1.0-p2artifacts.xml...`

**Comment by lppedd** [comment]
> the download of all the dependencies is slower on 3.0.0

Noticed the same. Also in my case the download progress report has disappeared in 3.0.0 >

**Comment by lppedd** [comment]
@Phillipus have you tried with `-D=tycho.p2.transport=ecf`? Can't right now but I'll try that too.

**Comment by laeubi** [comment]
> @Phillipus have you tried with `-D=tycho.p2.transport=ecf`? Can't right now but I'll try that too.

ECF is no longer supported. Neither maven nor Tycho is optimized for an empty repository, actually a lot of effort is taken into reusing stuff from the local repository to speed up things.

**Comment by Phillipus** [comment]
More testing shows that it's not actually the download being slower but some other processing at the point of `Writing P2 metadata for....` only for p2 bundles. All the other support bundles that Tycho/Maven downloads are fast.

**Comment by laeubi** [comment]
> only for p2 bundles.

What is a P2 bundle?

As said it all depends on many factors e.g. -T1C on a rather modern system gives often superior results over single threaded execution. At the same point it is quite "expensive" to download stuff depending on the updatesite used e.g. the usual eclipse updatesites need a lot of stuff being fetched (up to 70 request just to find out nothing has changed), then also the total size of the target platform matters much, and if you use complex dependency chains.

Also one can easily get false impressions if e.g. a project requires to resolve a target platform that it is "slow" while actually just other modules benefit much from the data computed there. There is some work in that area to make this more transparent, but its more low priority in the end. If this is crucial to someones business and likes to speed up the development in that area a [sponsoring](https://github.com/sponsors/laeubi?frequency=one-time) would allow me to assign more time-slots particular issue.

At least provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue is often the first step.

**Comment by Phillipus** [comment]
> What is a P2 bundle?

Not a technical term. I mean a bundle that Tycho downloads into the `.m2\repository\p2` directories.

All I'm doing is reporting what I've found - that 3.0.0 is twice as slow as 2.7.5. This is not a criticism.

> At least provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue is often the first step.

I think anyone who does an A/B test between 3.7.5 and 3.0.0 will find the same.

**Comment by Bananeweizen** [comment]
If someone with slow performance can post a performance measurement snapshot from Yourkit, VisualVM etc. then we could all investigate that together. Sampling instead of full profiling would be sufficient for starters.

**Comment by Phillipus** [comment]
> More testing shows that it's not actually the download being slower but some other processing at the point of `Writing P2 metadata for....`

More testing shows that assumption to be wrong. I downloaded the Eclipse p2 repository [here](https://download.eclipse.org/eclipse/downloads/drops4/R-4.25-202208311800/download.php?dropFile=repository-4.25.zip) and used that local copy in my pom rather than the online URL. Then I did the same builds A/B between Tycho 2.7.5 and 3.0.0 with a blank `.m2` directory each time. The timings were pretty much the same. So the download part seems to be slower in 3.0.0.

**Comment by laeubi** [comment]
As said, Tycho is not optimized for empty caches. Anyways we always try to improve if possible, for this we need a **minimal reproducer** with steps how to reproduce the undesired behavior.

Such a reproducer at best contains one single (public) update-site and one bundle consuming items and nothing else (e.g. no code but just some require-bundle to trigger the download of critical artifacts) that show the slowdown and where there are **measurable** performance degradation (e.g previously one minute now two minutes).

And this is something not "_anyone_" or "_someone_" can do, this is often the hardest part of fixing an issue but something we as the Tycho team can not afford as there are so many setups and side-effects (nexus mirrors, proxies, ...) and generally if we would have see this problem with our usual test suite would have fixed it beforehand.

**Comment by Phillipus** [comment]
> a minimal reproducer with steps how to reproduce the undesired behavior.

OK. Sample feature project and pom attached.

1. Delete your local `.m2` repository directory
2. Run `mvn clean package` on the project
3. Note how long it takes in the summary

Run steps 1-3 a few times to get an average time.

Then edit the pom file to change to `<tycho-version>2.7.5</tycho-version>` and do steps 1-3 again.

Of course connection speed will affect the timings. For me I get an average of 5:05 minutes for Tycho 3.0.0 and 1:40 minutes for Tycho 2.7.5.

[test tycho.zip](https://github.com/eclipse-tycho/tycho/files/9996993/test.tycho.zip)

**Comment by laeubi** [comment]
@Phillipus thanks for the example I'll take a look here, if this is crucial to someones business and likes to speed up the development in that area a [sponsoring](https://github.com/sponsors/laeubi?frequency=one-time) would allow me to assign more time-slots particular issue.

**Comment by Phillipus** [comment]
@laeubi I only report this issue here for science. ;-) As you say, once the artifacts have been downloaded Tycho speed is fine.

**Comment by laeubi** [comment]
@Phillipus Having an example is already great :-)

I'm just adding a note to all issues that are likely to "fall through" usual work of contributors, so if once someone stumble over it and feels it is a big concern for them can act upon it. We once fixed even an issue from Tycho 0.25 that way...

**Comment by laeubi** [comment]
@Phillipus I can verify your observation that Tycho 3+ is slower when downloading than Tycho 2.7 ... I now just need to find out what the root cause for this. There are some things to check here:

1. Tycho 3+ do not use gzip compression because usually files are already compressed and compressing a jar do not have much gain, still it might have a little influence but should not result in that much slow down given there are just about 200 files fetched.
2. Tycho 3+ creates a full cache, that is once you have downloaded all content you can go fully offline, of course this has some overhead but again given todays hard rive speeds  I don't expect much overhead here as well.
3. Tycho 3+ uses HtttpUrlconnection, it might be that we are hit by some system settings here that reduce e.c. keep alive handling. Again it is a bit strange that this should have such a large influence here.

So whats next is to take some measures here to get a better understanding whats going on.

**Comment by laeubi** [comment]
@Phillipus depending on your setup the consumer pom generation might trigger additional downloads, you can try to disable that feature for testing:

https://tycho.eclipseprojects.io/doc/latest/tycho-packaging-plugin/update-consumer-pom-mojo.html#skipPomGeneration

Beside that I was not able to identify a primary bottleneck, what makes the analysis a little bit hard is that mirrors are used here and these vary very much in their speed ... I even tried to use parallel downloads but that didn't changed much

**Comment by Phillipus** [comment]
> @Phillipus depending on your setup the consumer pom generation might trigger additional downloads, you can try to disable that feature for testing

Thanks for investigating. The pom generation setting didn't seem to make much, if any, difference.

**Comment by laeubi** [comment]
I made some experiments and it seems that not really the download itself is slower (tried URL vs Java11Client vs ApacheHttp) but the processing of the downloaded flies slow it down considerable ... I'll start some debugging on this.

**Comment by laeubi** [comment]
One can test this the following way:

1. run the build to download all stuff
2. then got to the m2 repo and delete the folder "p2"
3. even if everything is cached now it takes considerable time to build (data is jsut copied from the cache to the p2 folder)

**Comment by laeubi** [comment]
@Phillipus can you check if disabling the mirrors improves the situation in your case? If I use `-Dtycho.disableP2Mirrors=true` if have a donwloadtime of about 1:40 while with mirrors I get much worse times (about 5 minutes)

**Comment by Phillipus** [comment]
In fact Tycho 2.7.5 is slower with `-Dtycho.disableP2Mirrors=true` at 2:30 compared with 1:30 without.

**Comment by laeubi** [comment]
One problem seems that Tycho do not gives feedback about the download rate so slow mirrors are equally choose.

While this I also noticed a little problem here:
- https://github.com/eclipse-equinox/p2/issues/176

**Comment by Phillipus** [comment]
Thanks for looking at this!

**Comment by laeubi** [comment]
You can try out the current [tycho snapshot](https://github.com/eclipse/tycho/wiki#getting-tycho-snapshots) build to check if this improves things for your use-case.

**Comment by Phillipus** [comment]
> You can try out the current [tycho snapshot](https://github.com/eclipse/tycho/wiki#getting-tycho-snapshots) build to check if this improves things for your use-case.

Yes, like a rocket now! 🚀 

The test case takes 2:50 minutes now. Downloading the artifacts in the `p2` folder takes 1:10 minutes and that's where the bottleneck was.

Thanks!

**Comment by pcdavid** [comment]
Is this supposed to be fixed in Tycho 3.0.4 even when using mirrors?

I got hit by what looks a lot like this issue, with a build that seems "stuck" for several minutes in `assemble-maven-repository`. The CPU was at ~0% the whole time.

Investigating further it seems `SharedHttpCacheStorage$CacheLine.fetchFile` was blocked 
reading from 210.28.130.3, aka mirror.nju.edu.cn. The mirror seems fine, though a little slow, I get ~500KB/s downloading [a medium-size archive](https://mirror.nju.edu.cn/eclipse/sirius/updates/releases/7.0.7/org.eclipse.sirius-7.0.7-2021-06.zip) from there.

Using `-Dtycho.disableP2Mirrors=true` fixes the issue, but still feels relatively slow when starting from an empty Maven repo (05min 40s in my case).

**Comment by laeubi** [comment]
@pcdavid 3.0.4 was jsut released, you can try it. If not regarding back-ports please see https://github.com/eclipse-tycho/tycho/blob/master/CONTRIBUTING.md#backporting for details.

**Comment by pcdavid** [comment]
This was already with 3.0.4.

**Comment by Phillipus** [comment]
@pcdavid These are my timings to build our product with a clean `.m2` folder (target p2 repo of Eclipse 4.27):

Tycho 3.0.4
7:00 mins - `tycho.disableP2Mirrors` = false
4:40 mins - `tycho.disableP2Mirrors` = true

Tycho 4.0.0-SNAPSHOT
4:30 mins - `tycho.disableP2Mirrors` = false
4:00 mins - `tycho.disableP2Mirrors` = true

It seems the best improvement is with `tycho.disableP2Mirrors` = true

**Comment by laeubi** [comment]
So it seems no one has backported this (yet).

**Comment by lppedd** [comment]
With all the improvements 4.0.0 got, I'd suggest everyone to switch to that, even if snapshot.

I've been using it since December in prod with no issues. Not sure what the release plan is tho @laeubi

**Comment by Phillipus** [comment]
For the record, I have no complaints using 3.0.4. My comments here in this thread are for informational purposes. But, yeah, as @lppedd says, we have options to use the 4.0.0 snapshot. It's all good.

**Comment by laeubi** [comment]
Most likely after the 2023-06 release of eclipse.
