### ISSUE TITLE
Generalize protocol caching mechanism

### ISSUE THREAD

**Issue by lppedd** [eclipse-tycho/tycho#1887]
@laeubi we were talking some days ago about the fact FTP artifacts currently do not have a caching mechanism.

I would like to provide a patch for this, however currently the code around downloading seems really focused on HTTP, as I see it mentioned everywhere.

Could it be possible to generalize it so the caching implementations for other protocols can be contributed more easily?

**Comment by laeubi** [comment]
> Could it be possible to generalize it so the caching implementations for other protocols can be contributed more easily?

Not really, as each protocol has its own techniques for caching and up-to-date handling.

This would be the entry point for new protocols:
https://github.com/eclipse-tycho/tycho/blob/4808765baa326315147030792bf6b347d94fe155/p2-maven-plugin/src/main/java/org/eclipse/tycho/p2maven/transport/TychoRepositoryTransport.java#L202-L208

**Comment by lppedd** [comment]
@laeubi but take for example `HttpCache` and `HttpCacheConfig`:

```
public interface HttpCache {
  CacheEntry getCacheEntry(URI uri, Logger logger) throws FileNotFoundException;
  HttpCacheConfig getCacheConfig();
}
```

I think it's possible to generalize it, and then implement it for each protocol, like:

```
public interface ProtocolCache {
  boolean isProtocolSupported(URI uri);
  CacheEntry getCacheEntry(URI uri, Logger logger) throws FileNotFoundException;
  CacheConfig getCacheConfig();
}
```

```
public interface CacheEntry {
  long getLastModified(ProtocolTransportFactory transportFactory) throws IOException;
  File getCacheFile(ProtocolTransportFactory transportFactory) throws IOException;
}
```

You could in case cast to the effective implementation when appropriate.
I don't really like the idea of duplicating a lot of stuff, but if it's inevitable... I'll do it.

**Comment by laeubi** [comment]
You can generalize everything, the more interesting part would be what one really gain here.

I think one can for sure rename `HttpCacheConfig` > `CacheConfig` thatt quite generic and one actually won't need to reference that via the cache, but the rest is really optimized for Http and cannot really be reused. e.g. FTP has no mean for Headers or verbs like HTTP it also has no cache control and so on, so an FTP implementation would be much more simpler in this regard but will have other challenges... What other protocols we have? Probably something like webdav or ssh but again completely different concepts.

So making it "generic" in the end often means making it "complex" because you always have to think about the common base and often is more limiting, especially if it is only used internally.

So I think the easiest would be to start and see what is actually duplicated at all and if it makes sense to make things more complex just to safe a few lines...

**Comment by laeubi** [comment]
I now created
- https://github.com/eclipse-tycho/tycho/pull/1889

I think this should make it generic enough to add other handlers without much problems.

**Comment by laeubi** [comment]
You can now implement a `TransportProtocolHandler` component, the hint must be the supported protocol in lower case see for example:

https://github.com/eclipse-tycho/tycho/blob/master/p2-maven-plugin/src/main/java/org/eclipse/tycho/p2maven/transport/FileTransportProtocolHandler.java

**Comment by lppedd** [comment]
@laeubi thanks, that's a lot better! Will give it a go soon.

**Comment by lppedd** [comment]
@laeubi I need a pointer on how to access possible authentication details for a given repository URI host, so that I don't have to rely on the `anonymous` user

**Comment by laeubi** [comment]
```
@Requirement
MavenAuthenticator authenticator;
```
