### ISSUE TITLE
tycho-apitools-plugin:verify might be skipped if artifact was replaced

### ISSUE THREAD

**Issue by laeubi** [eclipse-tycho/tycho#2299]
Performing the API analysis is a quite expensive task (can take several seconds), if the main artifact is replaced with the baseline artifact it seems eminent that a API comparison is not really useful at all.

I therefore like to introduce a property that is set when the artifact is replaced with the baseline version and use this to skip the API Analysis.

@HannesWell @mickaelistria any concerns or side effects you can think of one should **not** do this? Given that most of the time one only changes a small subset of bundles with a PR, this might speed up builds a lot.

**Comment by HannesWell** [comment]
Sounds like a good idea.
Since with the artifact replacement the bits and version etc (just everything) should be completely equal I don't see any reason not to do it.

The only theoretical case I can think of that could cause issue is from the fact that often the baseline for the apitools and p2-metadata replacement are different. While the former uses the previous release, the latter uses the latest snapshots.
So it could happen, that one turns of the api-checks for some changes on the master/snapshots, the latest snapsho-repo then contains those changes and one later turns on the api-checks again. The the api-analysis will not complain at all because the artifact is replaced with the latest snapshot, altough there is actually a API difference compared to the latest release. And then on the next change that changes anything in the artifact one suddenly gets an API error that seems highly unrelated.

It is probably unlikely that this will happen by chance, but if we want to be paranoid I think it would be better to build in a fast-path in the `apitools:verify` goal that just compares the bits of reactor and baseline jar literally and skips its execution when they are identical.
Since the baseline artifacts are already cached in the local maven cache (or at least they will be once https://github.com/eclipse-tycho/tycho/pull/1328 is completed) I think that will be much faster already.

**Comment by laeubi** [comment]
The API baseline is always the latest release, so how could this occur here?
