### ISSUE TITLE
tycho.eclipseprojects.io is down

### ISSUE THREAD

**Issue by tivervac** [eclipse-tycho/tycho#2583]
The site for Tycho mojo documentation seems down.

The site I'm trying is `https://tycho.eclipseprojects.io/doc/latest/tycho-surefire-plugin/plugin-info.html`
If this isn't the most up-to-date link anymore, please point me in the right direction.

![image](https://github.com/eclipse-tycho/tycho/assets/3389524/725a3d11-3de3-4d70-bd9c-3a79ffe7e21b)

**Comment by laeubi** [comment]
I can open https://tycho.eclipseprojects.io/doc/latest/ so the page itself do not seems down but from there on the data seems gone.

The problem seems that there is no longer "plugin-info.html" for some reason.

https://github.com/eclipse-tycho/eclipse-tycho.github.io/tree/main/doc/3.0.5/tycho-surefire-plugin

**Comment by tivervac** [comment]
@laeubi How can I contribute to these docs? Doesn't seem like the repo where you fixed the issue supports issues.

**Comment by laeubi** [comment]
The docs are generated from the mojos javadoc beside some manually maintained ones here:

https://github.com/eclipse-tycho/tycho/tree/master/src/site

this is then uploaded here:
https://github.com/eclipse-tycho/eclipse-tycho.github.io
