### ISSUE TITLE
All statisfied requirements map to dependencies in InstallableUnitSlicer.computeDirectDependencies

### ISSUE THREAD

**Issue by merks** [eclipse-tycho/tycho#3197]
There are two cases where a requirement should not map to a dependency.

1. When `Requirement.getMax() == 0`, i.e., for so-called negative requirements.
2. When `IRequirement.getFilter() != null` and the filter is no applicable.

Mapping those two cases inappropriately can and does result in dependency cycles that break a build (for builds that worked for Tycho 2.x and 3.x).

Currently `org.eclipse.tycho.p2maven.InstallableUnitSlicer.computeDirectDependencies(Collection<IInstallableUnit>, IQueryable<IInstallableUnit>)` does not have enough context to determine if a filter is applicable or not, so the best we can do in the absence of such information is to assume the filter isn't applicable.

**Comment by laeubi** [comment]
@merks can you explain what context are needed? ws/os and maybe system properties?

**Comment by laeubi** [comment]
@merks I now have analyzed the problem and it is actually a bit more complex as initially thought:

1. first you are right that negative requirements are handled as regular ones, but the more general problem is that Tycho does not consider the `req.getMax()` at all, this is quite easy to fix and I'll provide a PR for that.
2. You are also right that filters are not considered, I have a solution to evaluate them but this can't be applied at the moment because it revealed another problem here see below.
3. The root cause of all evil (beside the rather trivial problem 1.)  is that currently we compute the project dependencies for each project and then hold them in a map. Based on that we now compute the inter-dependencies and projects to consider as an additional requirement. Now the following can (and does happen, e.g. for SWT build):

There is a project (look for example at [p2Inf.hostRequireFragment](https://github.com/eclipse-tycho/tycho/tree/master/tycho-its/projects/p2Inf.hostRequireFragment), where there is a [host](https://github.com/eclipse-tycho/tycho/tree/master/tycho-its/projects/p2Inf.hostRequireFragment/host) a [fragment](https://github.com/eclipse-tycho/tycho/tree/master/tycho-its/projects/p2Inf.hostRequireFragment/fragments/fragment-linux64) and the host requires the fragment with a [p2.inf](https://github.com/eclipse-tycho/tycho/blob/master/tycho-its/projects/p2Inf.hostRequireFragment/host/META-INF/p2.inf) but [disable the filter with a property](https://github.com/eclipse-tycho/tycho/blob/74f693b2a49680ccb69dd9445790a1d56d87149c/tycho-its/projects/p2Inf.hostRequireFragment/host/pom.xml#L23C8-L23C69).

The [consumer](https://github.com/eclipse-tycho/tycho/tree/master/tycho-its/projects/p2Inf.hostRequireFragment/consumer) requires the host and therefore _should_ require the fragment, and **do not disable this** by a property.

Because we compute the dependencies only once for a project, it is not included! Instead one needs to recompute the dependencies to be used based on the profile properties of the requesting project!

**Comment by laeubi** [comment]
While your testcase will be good to verify case (1) I think one needs a similar construct like this:
- https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/211

to reproduce case (2) fully, where there is a **bundle** that wants to require another **bundle** (not fragment!) with p2.inf [but only for one platform](https://github.com/eclipse-jdt/eclipse.jdt.debug/blob/168d4b5b5c757fd21904ad44e692f399d7874531/org.eclipse.jdt.launching/META-INF/p2.inf#L4) on a multi-platform build.

**Comment by merks** [comment]
You're awesome. 🎖️
