### ISSUE TITLE
`update-eclipse-metadata` does not listen to `releaseVersion`

### ISSUE THREAD

**Issue by toelen** [eclipse-tycho/tycho#3435]
Hi,

we are trying to use CI friendly tycho, and the version numbers in our poms are configured like this:

```
<version>${releaseVersion}${qualifier}</version>
```

In our build we want to update the MANIFEST.MF files using update-eclipse-metadata like this:

```
mvn -B  -DreleaseVersion=9.9.9 tycho-versions:update-eclipse-metadata 
```

I would expect that the MANIFEST.MF gets updated to `9.9.9.qualifier` but instead if fails with the following error:

```
[ERROR]   Version ${releaseVersion}${qualifier} is not valid for /Users/leentoelen/project/child/META-INF/MANIFEST.MF
```

Is `update-eclipse-metadata` incompatible with CI friendly properties?

**Comment by laeubi** [comment]
> Is update-eclipse-metadata incompatible with CI friendly properties?

That's quite likely... If you want you can provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue here are some examples:

https://github.com/eclipse-tycho/tycho/tree/main/tycho-its/projects/tycho-version-plugin

I just suppose you will see other problems with CI friendly versions if you not only want the qualifier affected but of course we can improve that as well.
